import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Body from "./(components)/Body"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Body>{children}</Body>
      </ClerkProvider>
    </html>
  );
}
